create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  device_id text not null unique,
  nickname text not null check (char_length(nickname) between 1 and 20),
  party_size integer not null check (party_size between 1 and 20),
  visit_date date not null,
  visit_time text not null,
  seating text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique check (char_length(email) between 3 and 254),
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 12),
  rating integer not null check (rating between 1 and 5),
  text text not null check (char_length(text) between 1 and 100),
  created_at timestamptz not null default now()
);

alter table public.reservations enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.reviews enable row level security;

grant usage on schema public to anon;
grant select, insert on public.reservations to anon;
grant select, insert on public.newsletter_subscribers to anon;
grant select, insert on public.reviews to anon;
grant usage, select on sequence public.reservations_id_seq to anon;
grant usage, select on sequence public.newsletter_subscribers_id_seq to anon;
grant usage, select on sequence public.reviews_id_seq to anon;

drop policy if exists "anyone can count reservations" on public.reservations;
drop policy if exists "anyone can create one device reservation" on public.reservations;
drop policy if exists "visitors can submit newsletter email" on public.newsletter_subscribers;
drop policy if exists "hidden console can read newsletter emails" on public.newsletter_subscribers;
drop policy if exists "visitors can read reviews" on public.reviews;
drop policy if exists "visitors can submit reviews" on public.reviews;

create policy "anyone can count reservations"
on public.reservations for select
to anon
using (true);

create policy "anyone can create one device reservation"
on public.reservations for insert
to anon
with check (true);

create policy "visitors can submit newsletter email"
on public.newsletter_subscribers for insert
to anon
with check (true);

create policy "hidden console can read newsletter emails"
on public.newsletter_subscribers for select
to anon
using (true);

create policy "visitors can read reviews"
on public.reviews for select
to anon
using (true);

create policy "visitors can submit reviews"
on public.reviews for insert
to anon
with check (true);
